language: go
go: 
 - "1.11.x"

os: osx

install: true

env:
  global:
    - GO111MODULE=on
    - CODECOV_TOKEN="fda83ffd-7216-4c61-a060-ed9cb8596f6e"

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_cache:
  - brew cleanup

before_install:
  - brew install lame

script: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)